---
- name: Run Tomcat inside Docker
  gather_facts: No
  hosts: aws
  become: yes
  become_method: sudo
  
  tasks:
     
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Pathon36
      yum:
        name: python36
        state: latest

    - name: Install docker
      command: python3 -m pip install docker

    - name: Docker login
      shell: 'docker login docker.com -u webyoga -p vegetarian767'

    - name: See running containers
      shell: docker ps --filter name=tomcat -q
      register: run_list

    - name: See all containers
      shell: docker ps --filter name=tomcat -aq
      register: stop_list

    - set_fact:
        diff: '{{ (stop_list.stdout_lines | difference(run_list.stdout_lines)) | length }}'
        run: '{{ run_list.stdout_lines | length }}'

    - name: Remove previous containers
      shell: docker stop tomcat && docker rm tomcat
      when: diff | int != 0

    - name: Run Tomcat container
      shell: 'docker pull danpil/nxbootcamp:orlov.alexey.health-check_service.1.0.0-snapshot && docker run -d -p 8085:8080 danpil/nxbootcamp:orlov.alexey.health-check_service.1.0.0-snapshot'
      when: diff | int != 0 or run | int == 0

